@startuml

left to right direction
actor Admin as "Администратор"

Admin --> (Управление аккаунтом)
Admin --> (Управление профилем)
Admin --> (Управление объявлениями)
Admin --> (Поиск и фильтрация)
Admin --> (Автоматическое сопоставление)
Admin --> (Связь через социальные сети)

@enduml

